### ISSUE TITLE
Token visible

### ISSUE THREAD

**Issue by FlowArg** [GregoireALP/Twitter-Bot-with-ISS-API#1]
Bonjour, je t'informe que les tokens sont visibles dans le fichier `config.js`. A l'avenir, met les hors du code.

**Comment by GregoireALP** [comment]
Oui je suis au courant mais le compte est juste un bot, ce n'est pas très
grave si quelqu'un a accès au compte.

**Comment by UnknowG** [comment]
"ce n'est pas très grave"
